require("ashar.plugins-setup")
require("ashar.core.options")
require("ashar.core.keymaps")
require("ashar.core.colorscheme")


require("ashar.plugins.treesitter")
require("ashar.plugins.notify")
require("ashar.plugins.nvim-tree")
require("ashar.plugins.nvim-cmp")
require("ashar.plugins.lualine")
require("ashar.plugins.telescope")
require("ashar.plugins.lsp.mason")
-- require("ashar.plugins.lsp.nvim-lint")
require("ashar.plugins.lsp.lspconfig")
require("ashar.plugins.lsp.llm")
require("ashar.plugins.llmgen")
require("ashar.plugins.autopairs")
require("ashar.plugins.autosave")
require("ashar.plugins.gitsigns")
require("ashar.plugins.troubley")
require("ashar.plugins.comment")
require("ashar.plugins.ufo")
require("ashar.plugins.neotest")
